name: Publish Package
on:
  repository_dispatch:
    types: [semantic-release]
jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com
          scope: '@rentpath'
      - run: |
          yarn config set @rentpath:registry https://npm.pkg.github.com
          yarn install --ignore-scripts
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test:coverage
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}